"""empty message

Revision ID: 250796f01a69
Revises: fdd0be230917
Create Date: 2022-11-05 11:36:15.341964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250796f01a69'
down_revision = 'fdd0be230917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book', 'author', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'author_id')
    # ### end Alembic commands ###
